CREATE SCHEMA "USER";

CREATE TABLE PERSONAS (
	NOMBRE VARCHAR(200)
);

--DROP TABLE PERSONAS;
--DROP SCHEMA "USER" RESTRICT;

--INSERT INTO PERSONAS (NOMBRE) VALUES ('Victor');
--INSERT INTO PERSONAS (NOMBRE) VALUES ('Maria');
--INSERT INTO PERSONAS (NOMBRE) VALUES ('Juan');
--INSERT INTO PERSONAS (NOMBRE) VALUES ('Alberto');